"use client"
import { Bricolage_Grotesque } from 'next/font/google'
import './globals.css'
import Header from '@/components/Layout/Header'
import Footer from '@/components/Layout/Footer'
import { ThemeProvider } from 'next-themes'
import NextTopLoader from 'nextjs-toploader';
import { Analytics } from "@vercel/analytics/next"
import { usePathname } from 'next/navigation'
import { SessionProvider } from "next-auth/react";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'CampFest 2025 ',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const pathname = usePathname();
  const isTicketsPage = pathname === '/tickets';

  return (
    <html lang='en' suppressHydrationWarning data-scroll-behavior="smooth">
      <body className={`${font.className} bg-black antialiased min-h-screen`}>
        <NextTopLoader color="#07be8a" />
        <SessionProvider>
          <div className="relative">
            <ThemeProvider
              attribute='class'
              enableSystem={true}
              defaultTheme='dark'>
              {!isTicketsPage && <Header />}
              <div className="pt-16">
                {children}
              </div>
              <Footer />
            </ThemeProvider>
            <a href="/tickets" className="fixed top-4 right-4 z-50 bg-green-500 text-white px-4 py-2 rounded-md shadow-lg md:hidden">Buy Tickets</a>
          </div>
        <Analytics />
        </SessionProvider>
      </body>
    </html>
  )
}
