import { Sponsor } from '@/types/sponsor';

export const sponsors: Sponsor[] = [
  {
    name: 'CampFest 2025',
    slug: 'campfest-2025',
    logo: '/images/terdimage/2025-JustCamping logo-8x8 flag-01.png',
    description: 'The main event organizer for CampFest 2025.',
    website: '#',
    facebook: 'https://facebook.com/campfest2025',
    instagram: 'https://instagram.com/campfest2025',
    twitter: 'https://twitter.com/campfest2025',
    linkedin: 'https://linkedin.com/company/campfest2025',
  },
  {
    name: 'Kamp Charlie Nae',
    slug: 'kamp-charlie-nae',
    logo: '/images/terdimage/kamp charlie nae.jpg',
    description: 'Providing unique camping experiences and outdoor adventures.',
    website: '#',
    facebook: 'https://facebook.com/kampcharlienae',
    instagram: 'https://instagram.com/kampcharlienae',
    twitter: 'https://twitter.com/kampcharlienae',
    linkedin: 'https://linkedin.com/company/kampcharlienae',
  },
  {
    name: 'CampFest Backgrounds',
    slug: 'campfest-backgrounds',
    logo: '/images/terdimage/campfestbg.png',
    description: 'Supplying stunning visual backdrops for our event.',
    website: '#',
    facebook: 'https://facebook.com/campfestbackgrounds',
    instagram: 'https://instagram.com/campfestbackgrounds',
    twitter: 'https://twitter.com/campfestbackgrounds',
    linkedin: 'https://linkedin.com/company/campfestbackgrounds',
  },
  {
    name: 'CampFest Images',
    slug: 'campfest-images',
    logo: '/images/terdimage/campfestimage.jpg',
    description: 'Capturing the best moments of CampFest with professional photography.',
    website: '#',
    facebook: 'https://facebook.com/campfestimages',
    instagram: 'https://instagram.com/campfestimages',
    twitter: 'https://twitter.com/campfestimages',
    linkedin: 'https://linkedin.com/company/campfestimages',
  },
  {
    name: 'Just Camping Logo',
    slug: 'just-camping-logo',
    logo: '/images/terdimage/2025-JustCamping logo-8x8 flag-01.png',
    description: 'Dedicated to promoting the joy of camping.',
    website: '#',
    facebook: 'https://facebook.com/justcamping',
    instagram: 'https://instagram.com/justcamping',
    twitter: 'https://twitter.com/justcamping',
    linkedin: 'https://linkedin.com/company/justcamping',
  },
];
