import { Sponsor } from '@/types/sponsor';

export const sponsors: Sponsor[] = [
  {
    name: 'Bluetti',
    slug: 'bluetti',
    logo: '/images/sponsorslogo/Bluetti Logo.png',
    description: 'Innovative power solutions for outdoor adventures.',
    website: '#',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    twitter: 'https://www.twitter.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Clapmoto',
    slug: 'clapmoto',
    logo: '/images/sponsorslogo/Clapmoto Logo.jpg',
    description: 'High-quality motor accessories and gear.',
    website: '#',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    twitter: 'https://www.twitter.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Gorilla',
    slug: 'gorilla',
    logo: '/images/sponsorslogo/Gorilla LOGO-cropped.JPG',
    description: 'Durable and reliable outdoor equipment.',
    website: '#',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    twitter: 'https://www.twitter.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'Maarte Campers Outdoor Gears',
    slug: 'maarte-campers-outdoor-gears',
    logo: '/images/sponsorslogo/Maarte Campers Outdoor Gears Logo.jpg',
    description: 'Stylish and functional outdoor camping gear.',
    website: '#',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    twitter: 'https://www.twitter.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'More Sponsors Soon 1',
    slug: 'more-sponsors-soon-1',
    description: 'Stay tuned for exciting new partnerships!',
    website: '#',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    twitter: 'https://www.twitter.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'More Sponsors Soon 2',
    slug: 'more-sponsors-soon-2',
    description: 'We are always looking for new collaborators.',
    website: '#',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    twitter: 'https://www.twitter.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'More Sponsors Soon 3',
    slug: 'more-sponsors-soon-3',
    description: 'Opportunity to join CampFest 2025.',
    website: '#',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    twitter: 'https://www.twitter.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'More Sponsors Soon 4',
    slug: 'more-sponsors-soon-4',
    description: 'Become a part of our growing family.',
    website: '#',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    twitter: 'https://www.twitter.com',
    linkedin: 'https://www.linkedin.com',
  },
  {
    name: 'More Sponsors Soon 5',
    slug: 'more-sponsors-soon-5',
    description: 'Reach out to us for sponsorship details.',
    website: '#',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    twitter: 'https://www.twitter.com',
    linkedin: 'https://www.linkedin.com',
  },
];
